config/routes.rb
Rails.application.routes.draw do
  resources :mining_types
  #get 'welcome/index'
  root 'welcome#index'
  resources :coins
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/coin.rb
class Coin < ApplicationRecord
    belongs_to :mining_type #, optional: true
end

app/models/mining_type.rb
class MiningType < ApplicationRecord
    has_many :coins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  def set_locale 
    if params[:locale]
      cookies[:locale] = params[:locale]
    end

    if cookies[:locale]
      if I18n.locale != cookies[:locale]
        I18n.locale = cookies[:locale]
      end
    end
  end
end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  before_action :set_coin, only: %i[ show edit update destroy ]
  before_action :set_mining_type_options, only: [:new, :create, :edit, :update]

  # GET /coins or /coins.json
  def index
    @coins = Coin.all
  end

  # GET /coins/1 or /coins/1.json
  def show
  end

  # GET /coins/new
  def new
    @coin = Coin.new
  end

  # GET /coins/1/edit
  def edit
  end

  # POST /coins or /coins.json
  def create
    @coin = Coin.new(coin_params)

    respond_to do |format|
      if @coin.save
        format.html { redirect_to coin_url(@coin), notice: "#{t('notice.coin_created')}" }
        format.json { render :show, status: :created, location: @coin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coins/1 or /coins/1.json
  def update
    respond_to do |format|
      if @coin.update(coin_params)
        format.html { redirect_to coin_url(@coin), notice: "#{t('notice.coin_updated')}" }
        format.json { render :show, status: :ok, location: @coin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @coin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coins/1 or /coins/1.json
  def destroy
    @coin.destroy
     
    respond_to do |format|
      format.html { redirect_to coins_url, notice: "#{t('notice.coin_deleted')}" }
      format.json { head :no_content }
    end
  end

  private
    def set_mining_type_options
      @mining_type_options = MiningType.all.pluck(:description, :id)
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_coin
      @coin = Coin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def coin_params
      params.require(:coin).permit(:description, :acronym, :url_image, :mining_type_id)
    end
end

app/controllers/mining_types_controller.rb
class MiningTypesController < ApplicationController
  before_action :set_mining_type, only: %i[ show edit update destroy ]

  # GET /mining_types or /mining_types.json
  def index
    @mining_types = MiningType.all
  end

  # GET /mining_types/1 or /mining_types/1.json
  def show
  end

  # GET /mining_types/new
  def new
    @mining_type = MiningType.new
  end

  # GET /mining_types/1/edit
  def edit
  end

  # POST /mining_types or /mining_types.json
  def create
    @mining_type = MiningType.new(mining_type_params)

    respond_to do |format|
      if @mining_type.save
        format.html { redirect_to mining_type_url(@mining_type), notice: "#{t('notice.mtype_created')}" }
        format.json { render :show, status: :created, location: @mining_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mining_types/1 or /mining_types/1.json
  def update
    respond_to do |format|
      if @mining_type.update(mining_type_params)
        format.html { redirect_to mining_type_url(@mining_type), notice: "#{t('notice.mtype_updated')}" }
        format.json { render :show, status: :ok, location: @mining_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @mining_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mining_types/1 or /mining_types/1.json
  def destroy
 
    @mining_type.destroy

    respond_to do |format|
      format.html { redirect_to mining_types_url, notice: "#{t('notice.mtype_deleted')}" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mining_type
      @mining_type = MiningType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def mining_type_params
      params.require(:mining_type).permit(:description, :acronym)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    cookies[:curso] = "Curso de Ruby on rails - [cookie]"#armazenado no Browser
    session[:curso] = "Curso de Ruby on rails - [session]"# armazenado no servidor
    
    @curso = "Rails"
  end
 
  
  end

app/helpers/application_helper.rb
module ApplicationHelper
    
 

  def data_br(data_us)
  data_us.strftime("%d/%m/%Y") 
  end

  def ambiente_rails
    if Rails.env.development?
      "#{t('development')}"
    elsif Rails.env.production?
      "#{t('production')}"
    else 
      "#{t('test')}"
    end
  end 
end

app/helpers/coins_helper.rb
module CoinsHelper
end

app/helpers/mining_types_helper.rb
module MiningTypesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/coins/_coin.html.erb
<div id="<%= dom_id coin %>">
 
  <tr>
    <th>
      <%= coin.description %>
    </th>

    <th>
      <%= coin.acronym %>
    </th>

    <th>
      <%= image_tag coin.url_image, width:25, height:25 %> 
    </th>
    
    <th>
      <%= link_to t('links.show'), coin %>
    <th>

    <th>
      <%= link_to t('links.edit'), edit_coin_path(coin)%>
    </th>


  </tr>
 
</div>

app/views/coins/_form.html.erb
<%= form_with(model: coin) do |form| %>
  <% if coin.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(coin.errors.count, "error")%> <%=t('textsave')%>:</h2>
      <ul>
        <% coin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="grid text-center col-md-6 g-col-6" >
    <div class="form-group">
      <%= form.label t('description'), style: "display: block" %></br>
      <%= form.text_field :description, class: "form-control grid text-center ", placeholder: "ex: Bitcoin" %></br>
    </div>

    <div class="form-group">
      <%= form.label t('acronym'), style: "display: block" %></br>
      <%= form.text_field :acronym, class: "form-control grid text-center", placeholder: "ex: BTC" %></br>
    </div>

    <div class="form-group">
      <%= form.label t('url_image'), style: "display: block" %></br>
      <%= form.text_field :url_image, class: "form-control grid text-center", placeholder: "ex: https://img.ur/bitcoin.png" %></br>
    </div>

    <div class="form-group">
      <p><%= form.label t('mining_types') %></p>
      <%= form.select("mining_type_id", @mining_type_options , { include_blank: t('links.select')}, class: "form-select grid text-center")%></br>
    </div>
   
    <div class="form-check">
      <%= form.submit nil, class: "btn btn-outline-light"%>
    </div>
  </div>
<% end %>

app/views/coins/edit.html.erb
<h1> <%= t('edit_coin')%> </h1>

<%= render "form", coin: @coin %>

<%= button_to t('links.delete'), @coin, form: { data: { turbo_confirm: t('text_confirm_del') } }, method: :delete, class: "bbtn btn-dark"%>
</br>
<div>
  <%= link_to t('links.back'), coins_path, class: "btn btn-dark" %>
  <%= link_to t('links.homepage'), root_path, class: "btn btn-dark"%>
</div>

app/views/coins/index.html.erb
<p style="color: green"> <%= notice %> </p>
<p> <strong> <%= t('dateword')%> </strong> <%= l(Date.today)%> <p>
<h1> <%=Coin.model_name.human(count: @coins.count)%> </h1>
<div id="Moedas">
  <table class="table table-dark table-hover table-sm">
    <thead>
      <tr>
        <th> <%= @coins.human_attribute_name(:description)%> </th>
        <th> <%=@coins.human_attribute_name(:acronym)%> </th>
        <th><%=@coins.human_attribute_name(:url_image)%></th>
      </tr>
    </thead>
    <tbody>
      <% @coins.each do |coin| %>
        <%= render coin %>
      <% end %>
    </tbody>
  </table>  
</div>
<div>
  <%= link_to t('links.add_new'), new_coin_path, class: "btn btn-dark" %>
  <%= link_to t('links.homepage'), root_path, class: "btn btn-dark" %>
</div>

app/views/coins/new.html.erb
<h1> <%=t('new_coin')%> </h1>

<%= render "form", coin: @coin %>

<br>

<div>
  <%= link_to t('links.back'), coins_path, class: "btn btn-dark" %>
</div>

app/views/coins/show.html.erb
<p style="color: blue"><%= notice %></p>


<form class=" grid text-center col-md-6 g-col-6" >
  <div class="form-group">
    <%= label_tag nil, @coin.class.human_attribute_name(:description), style: "display: block" %></br>
    <%= text_field_tag nil, @coin.description, class: "form-control", disabled: true%></br>
  </div>

  <div class="form-group">
    <%= label_tag nil, @coin.class.human_attribute_name(:acronym), style: "display: block" %></br>
    <%= text_field_tag nil, @coin.acronym, class: "form-control", disabled: true%></br>
  </div>

  <div class="form-group">
    <%= label_tag nil, @coin.class.human_attribute_name(:url_image), style: "display: block" %></br>
    <%= text_field_tag nil, @coin.url_image, class: "form-control", disabled: true%></br>
  </div>

  <div class="form-group">
    <%= label_tag nil, @coin.class.human_attribute_name(:mining_type), style: "display: block" %></br>
    <%= text_field_tag nil,@coin.mining_type.description , class: "form-control", disabled: true%></br>
  </div>
</form>

<%= link_to t('links.back'), coins_path, class: "btn btn-dark" %>
<%= link_to t('links.homepage'), root_path, class: "btn btn-dark"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CryptoJhow</title>
    
      
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => "reload" %> 
    
  
    <%= javascript_importmap_tags %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

  </head>

  <body>
    <div class="container-fluid">
      <ul class="nav justify-content-end">
        <li class="nav-item">
          <%= link_to 'Português', root_path(locale: 'pt-BR'), class: "nav-link"%> 
        </li>
        <li class="nav-item">
          <%= link_to 'English', root_path(locale: 'en'), class: "nav-link"%>
        </li>
      </ul>
      <%= yield %>
    </div>
  </body>
</html>

app/views/mining_types/_form.html.erb
<%= form_with(model: mining_type) do |form| %>
  <% if mining_type.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(mining_type.errors.count, "error")%> <%= t('textsave') %> :</h2>

      <ul>
        <% mining_type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="grid text-center col-md-6 g-col-6" >
    <div class="form-group" >
      <%= form.label t('description'), style: "display: block" %></br>
      <%= form.text_field :description, class: "form-control grid text-center ", placeholder: "ex: Proof of Work" %></br>
    </div>

    <div class="form-group">
      <%= form.label t('acronym'), style: "display: block" %></br>
      <%= form.text_field :acronym, class: "form-control grid text-center", placeholder: "ex: PoW" %></br>
    </div>

    <div class="form-check">
      <%= form.submit nil, class: "btn btn-outline-light" %></br>
    </div>
  </div> 
<% end %>

app/views/mining_types/_mining_type.html.erb
<div id="<%= dom_id mining_type %>">

  <tr>
    <th>
      <%= mining_type.description %>
    </th>

    <th>
       <%= mining_type.acronym %>
    </th>

    <th>
      <%=link_to t('links.show'),mining_type %>
    </th>

    <th>
      <%=link_to t('links.edit'), edit_mining_type_path(mining_type) %>
    </th>



  <tr>

</div>

app/views/mining_types/edit.html.erb
<h1> <%= t('edit_mining_type')%></h1>

<%= render "form", mining_type: @mining_type %>

<%= button_to t('links.delete'), @mining_type, form: { data: { turbo_confirm: t('text_confirm_del') } }, method: :delete, class: "btn btn-dark" %>
</br>
<div> 
  <%= link_to t('links.back'), mining_types_path, class: "btn btn-dark" %>
  <%= link_to t('links.homepage'), root_path, class: "btn btn-dark"%>
</div>

app/views/mining_types/index.html.erb
<p style="color: green"><%= notice %></p>

<h1><%= MiningType.model_name.human(count: @mining_types.count)%></h1>

<div id="mining_types">
  <table class="table table-dark table-hover">
    <thead>
      <tr>
        <th><%= @mining_types.human_attribute_name(:description) %></th>
        <th><%= @mining_types.human_attribute_name(:acronym) %></th>
       <p>
       </p>
      </tr>
    </thead>
    <tbody>
        <% @mining_types.each do |mining_type| %>
        <%= render mining_type %>
        <% end %>
    </tbody>
  </table>
</div>


<div>
  <%= link_to t('links.add_new'), new_mining_type_path, class: "btn btn-dark" %>
  <%= link_to t('links.homepage'), root_path, class: "btn btn-dark"%>
</div>

app/views/mining_types/new.html.erb
<h1><%=t('mining_types')%></h1>

<%= render "form", mining_type: @mining_type %>
<br>
<div>
  <%= link_to t('links.back'), mining_types_path, class: "btn btn-dark" %>
</div>

app/views/mining_types/show.html.erb
<p style="color: green"><%= notice %></p>
<form class=" grid text-center col-md-6 g-col-6" >
  <div class="form-group">
    <%= label_tag nil, @mining_type.class.human_attribute_name(:description), style: "display: block" %></br>
    <%= text_field_tag nil, @mining_type.description, class: "form-control", disabled: true%></br>    
  </div>
  <div class="form-group">
    <%= label_tag nil, @mining_type.class.human_attribute_name(:acronym), style: "display: block" %></br>
    <%= text_field_tag nil, @mining_type.acronym, class: "form-control", disabled: true%></br>
  </div>
</form>
<div>
  <%= link_to t('links.back'), mining_types_path, class: "btn btn-dark"%>
  <%= link_to t('links.homepage'), root_path, class: "btn btn-dark"%>  
</div>

app/views/welcome/_menu.html.erb
<%= link_to "#{Coin.model_name.human}", coins_path, class: "btn btn-outline-light"%>
<%= link_to "#{MiningType.model_name.human}",mining_types_path, class: "btn btn-outline-light"%>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <div class="container-fluid py-5">
      <header class="pb-3 mb-4 border-top">     
      </header>
        <body>
          <div class="row align-items-center grid text-center ">
            <div class="col-md-6">
              <div class="p-5 text-bg-dark rounded-3 ">
                <h1><%=t('hello')%> </h1>
                <p><%=t('text1')%></p>
                <p><%=t('text2')%></p>
                <%= render "menu" %>
              </div>
            </div>
          </div>
        </body>
      <footer class="pt-3 mt-4 text-muted ">
        <p> <strong><%=t('dateword')%>:</strong> <%= l(Date.today)%> <p>
        © 2022
      </footer>
    </div>
  </head>


</html>